services:
  mariadb:
    image: mariadb:12.0.2
    container_name: mariadb_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mariadb_dev
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pass
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mariadb_dev:/var/lib/mysql

volumes:
  mariadb_dev: