spring:
  application:
    name: todo

# Serialization
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
---
# Dev Datebase
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/mariadb_dev
    username: dev_user
    password: dev_pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
---
# Production Database
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false